%YAML 1.1
---
version: '>=0.0.0 || @head'
export: |

    project "ProgramOptions"
        kind "StaticLib"

        zpm.export [[
            includedirs "."
            cppdialect "C++11"
        ]]
...
